### ISSUE TITLE
It keeps asking for the password

### ISSUE THREAD

**Issue by hoegertn** [awslabs/awsprocesscreds#16]
I have a new issue now.

I configured Okta as provider and if I try to use it with `credential_process` it keeps asking for the password.

If I then run the command once directly in the command line and enter the password it works on subsequent calls as it uses the cached response.

What is the problem here?

**Comment by lingrlongr** [comment]
same problem here.  i have several profiles set up but rather than adding `--profile <profilename>` to every call, i tried to set `AWS_PROFILE` and `AWS_DEFAULT_PROFILE` to the profile i want to use and i keep getting prompted for the password.

**Comment by tylthal** [comment]
I am seeing the same issue as well federating with okta. If I run awsprocesscreds with the -v flag. I successfully receive the SAML assertion but then I am reprompted for my password continually in a loop.

**Comment by tylthal** [comment]
Does seem to be an issue with using the default profile. If I delete my aws config and re-run everything having just a named profile in the config it works fine.

**Comment by JordonPhillips** [comment]
That's odd that it's only occurring for the default profile. I'll look into it.

**Comment by peterahu** [comment]
I was able to reproduce this issue by removing my access keys for my default profile from `~/.aws/credentials`.  It seems like when botocore creates a client it expects at least one set of credentials for logging into aws and will try using the default profile as one credential provider.  So if the default profile doesn't have access keys (and there are no environment variables setting creds) then the password prompt from botocore shows up.

Here's how I dealt with the issue (#20) though I'm open to a more elegant solution too :)

**Comment by patrickdean** [comment]
I've experienced the same issue as well. I don't think the issue is with awsprocesscreds, but rather with botocore itself. Like @git-phu said, botocore expects some credentials upon creation. When it can't find them, it instead executes the credential_process found in the config (if credential_process is in the profile being used), thus calling awsprocesscreds again.

**Comment by JordonPhillips** [comment]
Ah, now I see the problem. It's like @patrickdean is saying. In botocore, when you create a client it will always try to resolve credentials even if you're creating a client with the special `UNSIGNED` signature version. I created an issue on botocore here: boto/botocore#1472 to track the issue.
