### ISSUE TITLE
ssl error - cant ignore

### ISSUE THREAD

**Issue by rjappala** [awslabs/awsprocesscreds#28]
Jordan
I have configured everything to have code commit to use processcreds to use AD to SSO to AWS, get token and then call code commit.
I have tested individual pieces - AD to SSO is working
Code commit with AWS Access key/secret key is working
then ur code is having issue - so tried to run tests in your repository and getting create_assertion failing.
Actual error ssl_error, i tried to config .gitconfig http.sslverify=false with url, and not working.

**Comment by rjappala** [comment]
I am getting following error when  i run code
git clone codecommit://adfs@lbwlesbtibco

Error:
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ADurl', port=443): Max retries exceeded with url: /adfs/ls/idpinitiatedSignOn.aspx?loginToRp=urn:amazon:webservices (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

Same URL - i can login to AWS SSO without any errors.

**Comment by JordonPhillips** [comment]
SSO isn't well supported right now, see #26 to track that feature.
